# Generated by Django 3.2.13 on 2022-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
